# Generated by Django 5.0.6 on 2024-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_vaccinesmodel_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinesmodel',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScheduleModel',
        ),
    ]
