# Generated by Django 5.0.6 on 2024-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_role_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=10, null=True),
        ),
    ]
